apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypdfcleaner
  labels:
    app: mypdfcleaner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mypdfcleaner
  template:
    metadata:
      labels:
        app: mypdfcleaner
    spec:
      containers:
      - name: mypdfcleaner
        image: mypdfcleaner:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
